### PR TITLE
Add an option to use Trianglify for the background

### PR DESCRIPTION
**Pull request by ullbergm**
This will give you the option to use Trianglify instead of a background picture for some random background art.

### CODE REVIEW

**Comment by KodeStar** [comment]
There are a lot of file changes here, but it looks like an interesting addition.  Do you have a screenshot of what it looks like?

**Comment by ullbergm** [comment]
The color and pattern changes each refresh.

If you want to try it out you can pull [ullbergm/heimdall](https://hub.docker.com/r/ullbergm/heimdall/)

trianglify

**Comment by KodeStar** [comment]
Stick a check on app.blade.php as to whether trianglify is actually being used before loading the trianglify scripts and I'll approve this.  Thanks for the contribution and sorry it's taken so long.

**Comment by ullbergm** [comment]
Good point, didn't think about that.

**Comment by kimpenhaus** [comment]
would love to see this in heimdall 👍

**Comment by lennvilardi** [comment]
How do you enable it ? I've got 2.2.2 from docker

**Comment by Macleykun** [comment]
Can this be merged @KodeStar ?

**Comment by KodeStar** [comment]
If the conflicts in the files are resolved... probably.

**Comment by EDIflyer** [comment]
This looks amazing - would be great to see this added if possible!

**Comment by EDIflyer** [comment]
bump to stop this going stale - would still be a nice addition

**Comment by EDIflyer** [comment]
bump to avoid being marked as stale

**Comment by j0nnymoe** [comment]
@EDIflyer it's likely this isn't going to get added as the OP hasn't replied in 4+ years. It's already been said that the conflicts need to be resolved first (plus it problems needed to be rebased aswell.)

**Comment by EDIflyer** [comment]
fair point, although @ullbergm looks to still be active on Github so hoping they might be up for a quick rebase/problem fix as it looks great in the screenshot :)

**Comment by ullbergm** [comment]
Been a while since I looked at this.. which branch should the PR be against? This old one is against 'master' but it looks like '2.x' is the default.

**Comment by ullbergm** [comment]
Created a new PR #1158 for the 2.x branch instead of master.

Also added an option to specify the random seed so that the background doesn't change between each transition to another page. If the seed is an empty string you will get a new random background each time.

**Comment by ullbergm** [comment]
Closing in favor of #1158

**Pull request closed without merging**
