### PR TITLE
Add Trianglify background option to the 2.x branch

### PR DESCRIPTION
**Pull request by ullbergm**
This will give you the option to use Trianglify instead of a background picture for some random background art.

Updated for the 2.x branch.

trianglify

### CODE REVIEW

**Comment by ullbergm** [comment]
I am not sure why the test is failing, when i run the container everything looks ok.
Capture

**Comment by KodeStar** [comment]
I think you need to update the test as well: https://github.com/linuxserver/Heimdall/blob/2.x/tests/Feature/SettingsTest.php

It's currently expecting to see "Homepage Search" after "Background Image"

**Comment by ullbergm** [comment]
I tried that but if you look at the output from the test, "Trianglify Random Seed" shows up twice, once under the [appearance section](https://github.com/linuxserver/Heimdall/actions/runs/4963816445/jobs/8883395545?pr=1158#step:10:204) and then again [after homepage search](https://github.com/linuxserver/Heimdall/actions/runs/4963816445/jobs/8883395545?pr=1158#step:10:243). But if you look at the screenshot from the webbrowser it only shows up once.
Did i mess something up with the settings id maybe?

**Comment by KodeStar** [comment]
I think 6 is already in use for the default search provider, use 12 and 13

**Comment by ullbergm** [comment]
> I think 6 is already in use for the default search provider, use 12 and 13

I changed it to 12 and 13 and the test still fails, the weird thing is that even though the text label talks about Trianglify, the link had setting 4 in it:
` <a href="http://localhost/settings/edit/4" title="Edit app.settings.trianglify_seed" class="secondary">`

**Comment by ullbergm** [comment]
Figured it out, it was a copy-paste issue on my end.

ps. Glad you added the tests, they caught my mistake.. :)

**Review by keriati — APPROVED** [review]
lgtm

**Comment by KodeStar** [comment]
@ullbergm we are just 10 days shy of the 5th anniversary of your initial PR, so thanks for persevering so we could finally get it in :D

**Pull request merged**
