### PR TITLE
chore: fix some typos in comments

### PR DESCRIPTION
**Pull request by goodactive**

### CODE REVIEW

**Review by wblew — APPROVED** [review]
simple typo fixes. no functional risks.

**Review by lyricnz — APPROVED** [review]

**Comment by lyricnz** [comment]
It's still valid, and trivial

**Comment by lyricnz** [comment]
The OP posted a perfectly valid PR. Stupid bot.

**Comment by lyricnz** [comment]
Come on @KodeStar

**Review by peternijssen — APPROVED** [review]

**Review by KodeStar — APPROVED** [review]

**Pull request merged**
