### PR TITLE
add search via select2 for application dropdown

### PR DESCRIPTION
**Pull request by TheDen**
I found searching the large list of dropdown apps to be difficult. This PR adds search to the dropdown via the provided [select2](https://select2.org/) package (see screenshots).

image

image

### CODE REVIEW

**Review by gfomichev — COMMENTED** [review]
Looks good

**Review by gfomichev — APPROVED** [review]

**Comment by TheDen** [comment]
@gfomichev Thanks for reviewing this PR. Any idea on why it's not merging/what else is required?

**Comment by gfomichev** [comment]
> @gfomichev Thanks for reviewing this PR. Any idea on why it's not merging/what else is required?

sorry, not the slightest idea

**Comment by amasolini** [comment]
@gfomichev who's in charge of approving and merging this kind of PRs? Who's the maintainer of this project?

**Review by hugoovf — APPROVED** [review]

**Comment by amasolini** [comment]
@0x1026 @gfomichev what else is needed for this PR to be merged? As I can see, there are 2 approvals already. Who else has "Write access" to approve it?

**Comment by hugoovf** [comment]
Well, the members which have permissions ignore this pr. Nice maintainers!

**Review by Argevollen — APPROVED** [review]

**Comment by mvdkleijn** [comment]
@KodeStar Would you mind chiming in here?

**Review by KodeStar — APPROVED** [review]

**Comment by KodeStar** [comment]
I've approved the changes as select2 is already included, I'm not sure it's really necessary (start typing the name of an app will take you to it anyway, or typing the name in the application name and selecting an option will also select the app) but if some people find it helpful I'm ok with it.

**Pull request merged**
